//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionUnion.Resources.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionUnion.Resources.Validation.ValidationRes", typeof(ValidationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field cannot be left blank..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        public static string User_CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("User_CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled..
        /// </summary>
        public static string User_Disabled {
            get {
                return ResourceManager.GetString("User_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email &apos;{0}&apos; already exists..
        /// </summary>
        public static string User_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("User_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail and password do not match..
        /// </summary>
        public static string User_EmailPassNotMatch {
            get {
                return ResourceManager.GetString("User_EmailPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail account verification.
        /// </summary>
        public static string User_EmailVerifSubject {
            get {
                return ResourceManager.GetString("User_EmailVerifSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the max. number of invalid attempts, you can try again in {0} minutes..
        /// </summary>
        public static string User_MaxInvalidLoginAttempts {
            get {
                return ResourceManager.GetString("User_MaxInvalidLoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your email in our records, you cannot recover your password..
        /// </summary>
        public static string User_MissingEmailCannotRecoverPassword {
            get {
                return ResourceManager.GetString("User_MissingEmailCannotRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your email in our records, you cannot reset your password..
        /// </summary>
        public static string User_MissingEmailCannotResetPassword {
            get {
                return ResourceManager.GetString("User_MissingEmailCannotResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot authenticate..
        /// </summary>
        public static string User_MissingPasswordCannotAuthenticate {
            get {
                return ResourceManager.GetString("User_MissingPasswordCannotAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Assistance.
        /// </summary>
        public static string User_PasswordRecoveryVerifSubject {
            get {
                return ResourceManager.GetString("User_PasswordRecoveryVerifSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Assistance.
        /// </summary>
        public static string User_PasswordResetVerifSubject {
            get {
                return ResourceManager.GetString("User_PasswordResetVerifSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string User_PasswordsNotMatch {
            get {
                return ResourceManager.GetString("User_PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserController_UserNotExist {
            get {
                return ResourceManager.GetString("UserController_UserNotExist", resourceCulture);
            }
        }
    }
}
